### PR TITLE
Revert "s/3.5/3.*"

### PR DESCRIPTION
**Pull request by akhilnarang**
Causes an error :D

This reverts commit fdf28cb82fb9ce6d7974582ed93811a93bde2479.

### CODE REVIEW

**Comment by MSF-Jarvis** [comment]
@akhilnarang Yeah noticed lol

**Comment by akhilnarang** [comment]
Also umm `os.exists()` dosen't exist xD

**Comment by akhilnarang** [comment]
`AttributeError: module 'os' has no attribute 'exists'`

**Comment by MSF-Jarvis** [comment]
Commit 6689fd58b00b20a49598c9bf20019e59fafe81a6 addresses all outstanding issues

**Pull request merged**
