### PR TITLE
manifest-manipulation: use python3

### PR DESCRIPTION
**Pull request by akhilnarang**
Arch dosen't have 3.5, just 3.6, I'm assuming that other distros might vary too, all should have 3 tho

Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

### CODE REVIEW

**Comment by MSF-Jarvis** [comment]
Mergeded

**Comment by akhilnarang** [comment]
y u no just pull tho, its fast forward af xD

**Comment by MSF-Jarvis** [comment]
git am XD

**Comment by akhilnarang** [comment]
Loool

**Pull request closed without merging**
